---
version: '3'

services:
  ftarc:
    container_name: ftarc
    build:
      context: ./build/ftarc
      dockerfile: Dockerfile
    image: dceoy/ftarc:latest
    user: ${UID}:${GID}
    userns_mode: host
    volumes:
      - .:/wd
    working_dir: /wd
    entrypoint:
      - /usr/local/bin/s3-sync-entrypoint
  sagvc:
    container_name: sagvc
    build:
      context: ./build/sagvc
      dockerfile: Dockerfile
    image: dceoy/sagvc:latest
    user: ${UID}:${GID}
    userns_mode: host
    volumes:
      - .:/wd
    working_dir: /wd
    entrypoint:
      - /usr/local/bin/s3-sync-entrypoint
  vanqc:
    container_name: vanqc
    build:
      context: ./build/vanqc
      dockerfile: Dockerfile
    image: dceoy/vanqc:latest
    user: ${UID}:${GID}
    userns_mode: host
    volumes:
      - .:/wd
    working_dir: /wd
    entrypoint:
      - /usr/local/bin/s3-sync-entrypoint
  replace-sam-read-group:
    container_name: replace-sam-read-group
    build:
      context: ./build/replace-sam-read-group
      dockerfile: Dockerfile
    image: dceoy/replace-sam-read-group:latest
    user: ${UID}:${GID}
    userns_mode: host
    volumes:
      - .:/wd
    working_dir: /wd
    entrypoint:
      - /usr/local/bin/s3-sync-entrypoint
