---
version: '3'

services:
  aws-ftarc:
    container_name: aws-ftarc
    build:
      context: ./ftarc
      dockerfile: Dockerfile
    image: dceoy/aws-ftarc:latest
    user: ${UID}:${GID}
    userns_mode: host
    volumes:
      - .:/wd
    working_dir: /wd
    entrypoint:
      - /usr/local/bin/s3-sync-entrypoint
